# stage 1

FROM node:alpine AS vms-site-build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm install && npm run build vms-site

# stage 2
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=vms-site-build /usr/src/app/dist/vms-site /usr/share/nginx/html
EXPOSE 80

